# Generated by Django 4.0 on 2021-12-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welbex',
            name='date',
            field=models.DateField(default='17.12.2021'),
        ),
    ]
